# Generated by Django 4.2.1 on 2025-06-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_availability_available_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='participants',
        ),
    ]
