# Generated by Django 4.2.1 on 2025-06-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sport'),
        ),
    ]
