# Generated by Django 4.2.1 on 2025-06-19 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_session_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(related_name='sessions_participated', through='accounts.Participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
